name: Build and Test

on:
  push:
    branches: [ "master", “staging”]
  pull_request:
    branches: [ "master", "staging" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: ls -la
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean test --file POM.xml
      working-directory: ${{github.workspace}}
